<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Pgvector.Vector for Knowledge.Embedding -->
    <PackageReference Include="pgvector" />
  </ItemGroup>

</Project>
