// <auto-generated />
using System;
using AgentContext.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AgentContext.Infrastructure.Migrations
{
    [DbContext(typeof(AgentContextDbContext))]
    [Migration("20260826125122_NormalizePostgresNaming")]
    partial class NormalizePostgresNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentContext.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_domains_workspace_id_name");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inference_configurations");

                    b.ToTable("inference_configurations", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeySecretRef")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("api_key_secret_ref");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inference_providers");

                    b.ToTable("inference_providers", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capability");

                    b.Property<Guid>("InferenceConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("inference_configuration_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_inference_routes");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_inference_routes_provider_id");

                    b.HasIndex("InferenceConfigurationId", "Capability")
                        .IsUnique()
                        .HasDatabaseName("uq_inference_routes_inference_configuration_id_capability");

                    b.ToTable("inference_routes", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("ConflictGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("conflict_group_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<DateTimeOffset?>("LastConfidenceDecayAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confidence_decay_at_utc");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_knowledge");

                    b.HasIndex("ConflictGroupId")
                        .HasDatabaseName("ix_knowledge_conflict_group_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_embedding_hnsw")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_l2_ops" });

                    b.HasIndex("SourceSessionId")
                        .HasDatabaseName("ix_knowledge_source_session_id");

                    b.HasIndex("DomainId", "Status")
                        .HasDatabaseName("ix_knowledge_domain_id_status");

                    b.HasIndex("WorkspaceId", "SourceSessionId")
                        .HasDatabaseName("ix_knowledge_workspace_id_source_session_id");

                    b.HasIndex("Status", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_knowledge_status_created_at_utc_id");

                    b.HasIndex("Status", "UpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_knowledge_status_updated_at_utc_id");

                    b.HasIndex("Status", "Confidence", "UpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_knowledge_status_confidence_updated_at_utc_id");

                    b.ToTable("knowledge", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memberships_user_id");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_memberships_workspace_id_user_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_name");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conclusion");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("FullContext")
                        .HasColumnType("text")
                        .HasColumnName("full_context");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<bool>("Remembered")
                        .HasColumnType("boolean")
                        .HasColumnName("remembered");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary_json");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_sessions_domain_id");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_sessions_status_next_attempt_at_utc");

                    b.HasIndex("WorkspaceId", "DomainId")
                        .HasDatabaseName("ix_sessions_workspace_id_domain_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("SourceDigest")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_digest");

                    b.Property<string>("SourceRevision")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_revision");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_skills_domain_id");

                    b.HasIndex("PreviousVersionId")
                        .HasDatabaseName("ix_skills_previous_version_id");

                    b.HasIndex("WorkspaceId", "DomainId", "Slug")
                        .HasDatabaseName("ix_skills_workspace_id_domain_id_slug");

                    b.HasIndex("WorkspaceId", "DomainId", "Slug", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_skills_workspace_id_domain_id_slug_version");

                    b.ToTable("skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_skills_source_type", "source_type IS NULL OR source_type IN ('manual', 'zip', 'skills_sh', 'local_copy')");

                            t.HasCheckConstraint("ck_skills_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Usage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CachedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_input_tokens");

                    b.Property<string>("Capability")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capability");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("InferenceRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("inference_route_id");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_usage");

                    b.HasIndex("InferenceRouteId")
                        .HasDatabaseName("ix_usage_inference_route_id");

                    b.HasIndex("SessionId", "CreatedAtUtc")
                        .HasDatabaseName("ix_usage_session_id_created_at_utc");

                    b.HasIndex("Source", "CreatedAtUtc")
                        .HasDatabaseName("ix_usage_source_created_at_utc");

                    b.ToTable("usage", null, t =>
                        {
                            t.HasCheckConstraint("ck_usage_cached_input_subset", "cached_input_tokens <= input_tokens");

                            t.HasCheckConstraint("ck_usage_capability_valid", "capability IS NULL OR capability IN ('Chat', 'Embedding')");

                            t.HasCheckConstraint("ck_usage_source_relationships", "(source = 'reported_session' AND session_id IS NOT NULL AND inference_route_id IS NULL AND capability IS NULL) OR source = 'learning_engine'");

                            t.HasCheckConstraint("ck_usage_source_valid", "source IN ('reported_session', 'learning_engine')");

                            t.HasCheckConstraint("ck_usage_tokens_non_negative", "input_tokens >= 0 AND cached_input_tokens >= 0 AND output_tokens >= 0");
                        });
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Domain", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Domains")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domains_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceRoute", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.InferenceConfiguration", "InferenceConfiguration")
                        .WithMany("Routes")
                        .HasForeignKey("InferenceConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inference_routes_inference_configurations_inference_configuration_id");

                    b.HasOne("AgentContext.Domain.Entities.InferenceProvider", "Provider")
                        .WithMany("Routes")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inference_routes_inference_providers_provider_id");

                    b.Navigation("InferenceConfiguration");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Knowledge", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.Domain", "Domain")
                        .WithMany("Knowledge")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_domains_domain_id");

                    b.HasOne("AgentContext.Domain.Entities.Session", "SourceSession")
                        .WithMany("Knowledge")
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_knowledge_sessions_source_session_id");

                    b.HasOne("AgentContext.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_workspaces_workspace_id");

                    b.Navigation("Domain");

                    b.Navigation("SourceSession");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Membership", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");

                    b.HasOne("AgentContext.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Session", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sessions_domains_domain_id");

                    b.HasOne("AgentContext.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_workspaces_workspace_id");

                    b.Navigation("Domain");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Skill", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.Domain", "Domain")
                        .WithMany("Skills")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_domains_domain_id");

                    b.HasOne("AgentContext.Domain.Entities.Skill", "PreviousVersion")
                        .WithMany("NextVersions")
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_skills_previous_version_id");

                    b.HasOne("AgentContext.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_workspaces_workspace_id");

                    b.Navigation("Domain");

                    b.Navigation("PreviousVersion");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Usage", b =>
                {
                    b.HasOne("AgentContext.Domain.Entities.InferenceRoute", "InferenceRoute")
                        .WithMany()
                        .HasForeignKey("InferenceRouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usage_inference_routes_inference_route_id");

                    b.HasOne("AgentContext.Domain.Entities.Session", "Session")
                        .WithMany("Usage")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_usage_sessions_session_id");

                    b.Navigation("InferenceRoute");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Domain", b =>
                {
                    b.Navigation("Knowledge");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceConfiguration", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.InferenceProvider", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Session", b =>
                {
                    b.Navigation("Knowledge");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Skill", b =>
                {
                    b.Navigation("NextVersions");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("AgentContext.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Memberships");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
